import { type NextPage } from "next";
import Head from "next/head";
import MainLayout from "@/components/layouts/MainLayout";
import ApplicationForm from "@/components/content/apply/ApplicationForm";

const Page: NextPage = () => {
  return (
    <>
      <Head>
        <title>Apply</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <div className="flex flex-col items-center justify-center">
          <h1 className="text-2xl">Apply</h1>
          <ApplicationForm />
        </div>
      </MainLayout>
    </>
  );
};

export default Page;