import { type NextPage } from "next";
import Head from "next/head";
import MainLayout from "@/components/layouts/MainLayout";

type HomeProps = {};

const Home: NextPage<HomeProps> = () => {
  return (
    <>
      <Head>
        <title>Engnr.</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <div className="flex min-h-screen flex-col items-center overflow-hidden relative">
          <div className="w-full h-[150%] md:w-1/2 md:h-auto absolute top-0">
            <img
              src="/images/bannerImage.webp" // adjust this according to where the image is in the public directory
              className="w-full h-full object-cover" 
              alt="heroImage1"
            />
          </div>
        </div>
      </MainLayout>
    </>
  );
};

export default Home;